import sys
import smtplib
import json
import html
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

def badge(status):
    colors = {
        "HEALTHY": "#28a745",
        "WARNING": "#ff9800",
        "RUNNING": "#28a745",
        "STOPPED": "#dc3545",
        "ATTENTION REQUIRED": "#dc3545"
    }

    color = colors.get(status, "#6c757d")

    return f"""
    <span style="
        background:{color};
        color:white;
        padding:5px 12px;
        border-radius:15px;
        font-weight:bold;
        font-size:13px;">
        {html.escape(status)}
    </span>
    """
# ----------------------------------------------------
# Load configuration
# ----------------------------------------------------
config = {}

with open("/home/bchand/linux-server-health-monitor/config.env") as f:
    for line in f:
        line = line.strip()

        if not line or "=" not in line:
            continue

        key, value = line.split("=", 1)
        config[key] = value

SENDER_EMAIL = config["SENDER_EMAIL"]
APP_PASSWORD = config["APP_PASSWORD"]
RECEIVER_EMAIL = config["RECEIVER_EMAIL"]

# ----------------------------------------------------
# Read report generated by monitor.sh
# ----------------------------------------------------
with open(sys.argv[1], "r") as f:
    report = json.load(f)
# ----------------------------------------------------
# Determine subject
# ----------------------------------------------------

plain_text = f"""
Linux Server Health Monitor

Hostname: {report['hostname']}

Overall Status: {report['overall_status']}

CPU: {report['resources']['cpu']['usage']}%

Memory: {report['resources']['memory']['usage']}%

Disk: {report['resources']['disk']['usage']}%

This email contains an HTML report. If you cannot view it, use an HTML-capable email client.
"""

if "ATTENTION REQUIRED" in plain_text:
    subject = "[CRITICAL] Linux Server Health Monitor Alert"
else:
    subject = "[OK] Linux Server Health Monitor Report"

# ----------------------------------------------------
# Convert report into HTML
# ----------------------------------------------------
html_report = plain_text.replace("&", "&amp;")
html_report = html_report.replace("<", "&lt;")
html_report = html_report.replace(">", "&gt;")

# Highlight important keywords
html_report = html_report.replace(
    "HEALTHY",
    '<span style="color:green;font-weight:bold;">HEALTHY</span>'
)

html_report = html_report.replace(
    "WARNING",
    '<span style="color:#d97706;font-weight:bold;">WARNING</span>'
)

html_report = html_report.replace(
    "RUNNING",
    '<span style="color:green;font-weight:bold;">RUNNING</span>'
)

html_report = html_report.replace(
    "STOPPED",
    '<span style="color:red;font-weight:bold;">STOPPED</span>'
)

html_report = html_report.replace(
    "ATTENTION REQUIRED",
    '<span style="color:red;font-weight:bold;">ATTENTION REQUIRED</span>'
)

resource_table = f"""
<table style="
width:100%;
border-collapse:collapse;
margin-top:15px;">

<tr style="background:#f2f2f2;">
<th style="padding:10px;border:1px solid #ddd;">Resource</th>
<th style="padding:10px;border:1px solid #ddd;">Usage</th>
<th style="padding:10px;border:1px solid #ddd;">Status</th>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;">CPU</td>
<td style="padding:10px;border:1px solid #ddd;">{report['resources']['cpu']['usage']}%</td>
<td style="padding:10px;border:1px solid #ddd;">{badge(report['resources']['cpu']['status'])}</td>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;">Memory</td>
<td style="padding:10px;border:1px solid #ddd;">{report['resources']['memory']['usage']}%</td>
<td style="padding:10px;border:1px solid #ddd;">{badge(report['resources']['memory']['status'])}</td>
</tr>

<tr>
<td style="padding:10px;border:1px solid #ddd;">Disk</td>
<td style="padding:10px;border:1px solid #ddd;">{report['resources']['disk']['usage']}%</td>
<td style="padding:10px;border:1px solid #ddd;">{badge(report['resources']['disk']['status'])}</td>
</tr>

</table>
"""

service_rows = ""

for service in report["services"]:

    service_rows += f"""
<tr>
<td style="padding:10px;border:1px solid #ddd;">
{service['name']}
</td>

<td style="padding:10px;border:1px solid #ddd;">
{badge(service['status'])}
</td>
</tr>
"""

service_table = f"""
<table style="
width:100%;
border-collapse:collapse;
margin-top:15px;">

<tr style="background:#f2f2f2;">
<th style="padding:10px;border:1px solid #ddd;">Service</th>
<th style="padding:10px;border:1px solid #ddd;">Status</th>
</tr>

{service_rows}

</table>
"""
server_info = f"""
<table style="
width:100%;
border-collapse:collapse;">

<tr><td><b>Hostname</b></td><td>{report['hostname']}</td></tr>
<tr><td><b>Operating System</b></td><td>{report['os']}</td></tr>
<tr><td><b>Kernel</b></td><td>{report['kernel']}</td></tr>
<tr><td><b>IP Address</b></td><td>{report['ip']}</td></tr>
<tr><td><b>Generated At</b></td><td>{report['time']}</td></tr>

</table>
"""


html_body = f"""
<html>

<body style="
font-family:Arial,sans-serif;
background:#f5f5f5;
padding:20px;">

<div style="
max-width:900px;
margin:auto;
background:white;
border-radius:10px;
box-shadow:0 0 10px rgba(0,0,0,.1);">

<div style="
background:#1565C0;
color:white;
padding:20px;
font-size:30px;
font-weight:bold;
text-align:center;">

Linux Server Health Monitor

</div>

<div style="padding:25px;">

<h2>Server Information</h2>

{server_info}

<hr>

<h2>Overall Status</h2>

{badge(report["overall_status"])}

<hr>

<h2>Resource Summary</h2>

{resource_table}

<hr>

<h2>Service Status</h2>

{service_table}

<hr>

<h2>Recommended Actions</h2>

<ul>

<li>Restart failed services if any.</li>

<li>Investigate components in WARNING state.</li>

<li>Review application and system logs.</li>

<li>Verify server resource utilization.</li>

</ul>

</div>

<div style="
background:#eeeeee;
padding:15px;
text-align:center;
font-size:12px;">

Generated automatically by Linux Server Health Monitor v2.3

</div>

</div>

</body>

</html>
"""


# ----------------------------------------------------
# Create email
# ----------------------------------------------------
msg = MIMEMultipart("alternative")

msg["Subject"] = subject
msg["From"] = SENDER_EMAIL
msg["To"] = RECEIVER_EMAIL

msg.attach(MIMEText(plain_text, "plain"))
msg.attach(MIMEText(html_body, "html"))

# ----------------------------------------------------
# Send email
# ----------------------------------------------------
try:
    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(SENDER_EMAIL, APP_PASSWORD)
        smtp.sendmail(
            SENDER_EMAIL,
            RECEIVER_EMAIL,
            msg.as_string()
        )

    print("Email sent successfully.")

except Exception as e:
    print("Error:", e)
